### ISSUE TITLE
sysjitter can run on the cores other than the cores specified

### ISSUE THREAD

**Issue by donghaiqiao** [alexeiz/sysjitter#1]
I pulled over the source from this repo, then compiled code and ran sysjitter on a Intel machine with a command as below
 
# ./sysjitter --runtime 30 --cores 1,2 200
core_i: 0 8
threshold(ns): 200 200
cpu_mhz: 2500 2500
runtime(ns): 29999116255 29999113075
runtime(s): 29.999 29.999
int_n: 30489 30733
int_n_per_sec: 1016.330 1024.464
int_min(ns): 1215 1080
int_median(ns): 1689 1594
int_mean(ns): 2484 2685
int_90(ns): 1864 1902
int_99(ns): 10866 11044
int_999(ns): 170671 171572
int_9999(ns): 384572 692862
int_99999(ns): 643410 984783
int_max(ns): 643410 984783
int_total(ns): 75743397 82545295
int_total(%): 0.252 0.275

I wanted sysjitter to run on the cores 1 and 2, however, it actually ran on the cores 0 and 8 as this output indicated.  I am not sure what I did wrong or this is an issue.

By the way, this machine has 24 cores. Except core 0 and 8, others are all isolated through the configuration shown as below from the file /etc/tuned/cpu-partitioning-variables.conf

housekeeping_cpus=0,8
no_balance_cores=1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
isolated_cores=1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23

Here is the output of lscpu and /proc/cmdline if these data can help diagnose the issue
# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              24
On-line CPU(s) list: 0-23
Thread(s) per core:  2
Core(s) per socket:  6
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               45
Model name:          Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz
Stepping:            7
CPU MHz:             1200.151
BogoMIPS:            4999.70
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            15360K
NUMA node0 CPU(s):   0,2,4,6,8,10,12,14,16,18,20,22
NUMA node1 CPU(s):   1,3,5,7,9,11,13,15,17,19,21,23
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts md_clear flush_l1d

# cat /proc/cmdline
BOOT_IMAGE=(hd0,msdos1)/vmlinuz-4.18.0-147.el8.x86_64 root=/dev/mapper/rhel_dell--pet620--01-root ro crashkernel=auto resume=/dev/mapper/rhel_dell--pet620--01-swap rd.lvm.lv=rhel_dell-pet620-01/root rd.lvm.lv=rhel_dell-pet620-01/swap console=ttyS0,115200n81 skew_tick=1 nohz=on nohz_full=1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 rcu_nocbs=1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 tuned.non_isolcpus=00000101 intel_pstate=disable nosoftlockup

**Comment by alexeiz** [comment]
Thanks for the report.  This is not my tool though, I just modified it for my purpose slightly.

You can contact the author at "David Riddoch <david@riddoch.org.uk>".  Or `git checkout` the first commit if you want the original behavior.

**Comment by zolt4n** [comment]
here is the diff to fix the issue:
```diff

diff --git a/sysjitter.c b/sysjitter.c
index 76b24b8..515449d 100644
--- a/sysjitter.c
+++ b/sysjitter.c
@@ -698,7 +698,6 @@ int main(int argc, char* argv[])
       sscanf(argv[0], "%u%c", &g.threshold_nsec, &dummy) != 1 )
     usage_err();

-  int nprocs = get_nprocs_conf();
   cpu_set_t cpus;
   sched_getaffinity(getpid(), sizeof cpus, &cpus);

@@ -716,17 +715,14 @@ int main(int argc, char* argv[])
   TEST( threads = malloc(n_cores * sizeof(threads[0])) );
   g.n_threads = n_cores;

-  int cur_proc = 0;
-  for (int i = 0; i != n_cores; ++i, ++cur_proc)
+  for (int i = 0; i != n_cores; ++i)
   {
-    while (!CPU_ISSET(cur_proc, &cpus) && cur_proc != nprocs)
-        ++cur_proc;
-
-    if (cur_proc != nprocs)
+    int cur_proc = cores[i];
+    if (CPU_ISSET(cur_proc, &cpus))
       threads[i].core_i = cur_proc;
     else
     {
-      puts("error: reached nprocs limit");
+      puts("error: Could not set affinity to thread");
       exit(1);
     }
   }

```

**Comment by alexeiz** [comment]
I suggest to use the code from https://github.com/Xilinx-CNS/cns-sysjitter.  It behaves as you'd expect regarding the CPU core assignment.
